<?php if ($user != '') : ?><?php function st_stallion_update() {
$options1 = get_option('theme-stallion-seo-theme-options');
if(themeID()==''){$options1['themeID'] = '';}
if(st_version_number()!='6.2'){$options1['st_version_number'] = '6.2';}
if(st_adsense_on()==''){$options1['st_adsense_on'] = '1';}
if(st_adsense_pub()==''){$options1['st_adsense_pub'] = 'pub-8325072546567078';}
if(st_clickbank_on()==''){$options1['st_clickbank_on'] = '0';}
if(st_clickbank_user()==''){$options1['st_clickbank_user'] = 'morearning';}
if(st_chitika_on()==''){$options1['st_chitika_on'] = '0';}
if(st_chitika_pub()==''){$options1['st_chitika_pub'] = 'clickity';}
if(st_adsense_main_ad()==''){$options1['st_adsense_main_ad'] = '0';}
if(st_chitika_main_ad()==''){$options1['st_chitika_main_ad'] = '4';}
if(st_clickbank_main_ad()==''){$options1['st_clickbank_main_ad'] = '8';}
if(st_update_now()==''){$options1['st_update_now'] = '0';}
if(st_update_now()=='1'){$options1['st_update_now'] = '0';}
if(st_my_defaults()==''){$options1['st_my_defaults'] = '0';}
update_option('theme-stallion-seo-theme-options', $options1);

$st_options2 = get_option('theme-stallion-seo-theme-adsense');
if(st_googlesearch()==''){$st_options2['st_googlesearch'] = '2q49p6httws';}
if(st_adsense_float()==''){$st_options2['st_adsense_float'] = 'fadright';}
if(st_adsense_switch()==''){$st_options2['st_adsense_switch'] = '0';}
if(st_googleborder()==''){$st_options2['st_googleborder'] = 'FFFFFF';}
if(st_googlebg()==''){$st_options2['st_googlebg'] = 'FFFFFF';}
if(st_googlelink()==''){$st_options2['st_googlelink'] = '000000';}
if(st_googleurl()==''){$st_options2['st_googleurl'] = '4D4D4D';}
if(st_googletext()==''){$st_options2['st_googletext'] = '4D4D4D';}
if(st_gaduifeature()==''){$st_options2['st_gaduifeature'] = '0';}
if(st_adsense_con1_head()==''){$st_options2['st_adsense_con1_head'] = '0';}
if(st_adsense_con1_bg()==''){$st_options2['st_adsense_con1_bg'] = 'div';}
if(st_adsense_con7_head()==''){$st_options2['st_adsense_con7_head'] = '0';}
if(st_adsense_con7_bg()==''){$st_options2['st_adsense_con7_bg'] = 'div';}
if(st_adsense_lnk5_head()==''){$st_options2['st_adsense_lnk5_head'] = '1';}
if(st_adsense_lnk5_bg()==''){$st_options2['st_adsense_lnk5_bg'] = 'div';}
if(st_adsense_con1()==''){$st_options2['st_adsense_con1'] = '0';}
if(st_adsense_con2()==''){$st_options2['st_adsense_con2'] = '0';}
if(st_adsense_con3()==''){$st_options2['st_adsense_con3'] = '0';}
if(st_adsense_con7()==''){$st_options2['st_adsense_con7'] = '1';}
if(st_adsense_lnk4()==''){$st_options2['st_adsense_lnk4'] = '1';}
if(st_adsense_lnk5()==''){$st_options2['st_adsense_lnk5'] = '0';}
if(st_adsense_lnk6()==''){$st_options2['st_adsense_lnk6'] = '1';}
if(st_adsense_lnk6_pm()==''){$st_options2['st_adsense_lnk6_pm'] = '0';}
if(st_adsense_lnk6_sing()==''){$st_options2['st_adsense_lnk6_sing'] = '0';}
if(st_adsense_typ1()==''){$st_options2['st_adsense_typ1'] = '0';}
if(st_adsense_typ2()==''){$st_options2['st_adsense_typ2'] = '0';}
if(st_adsense_typ3()==''){$st_options2['st_adsense_typ3'] = '0';}
if(st_adsense_typ7()==''){$st_options2['st_adsense_typ7'] = '0';}
if(st_adsense_siz1()==''){$st_options2['st_adsense_siz1'] = '11';}
if(st_adsense_siz2()==''){$st_options2['st_adsense_siz2'] = '6';}
if(st_adsense_siz3()==''){$st_options2['st_adsense_siz3'] = '2';}
if(st_adsense_siz4()==''){$st_options2['st_adsense_siz4'] = '29';}
if(st_adsense_siz5()==''){$st_options2['st_adsense_siz5'] = '25';}
if(st_adsense_siz6()==''){$st_options2['st_adsense_siz6'] = '29';}
if(st_adsense_siz7()==''){$st_options2['st_adsense_siz7'] = '6';}
if(st_adsense_chan1()==''){$st_options2['st_adsense_chan1'] = '';}
if(st_adsense_chan2()==''){$st_options2['st_adsense_chan2'] = '';}
if(st_adsense_chan3()==''){$st_options2['st_adsense_chan3'] = '';}
if(st_adsense_chan4()==''){$st_options2['st_adsense_chan4'] = '';}
if(st_adsense_chan5()==''){$st_options2['st_adsense_chan5'] = '';}
if(st_adsense_chan6()==''){$st_options2['st_adsense_chan6'] = '';}
if(st_adsense_chan7()==''){$st_options2['st_adsense_chan7'] = '';}
if(st_gadalternate_ad()==''){$st_options2['st_gadalternate_ad'] = '';}
update_option('theme-stallion-seo-theme-adsense', $st_options2);

$st_options3 = get_option('theme-stallion-seo-theme-chitika');
if(st_chitika_float()==''){$st_options3['st_chitika_float'] = 'fadright';}
if(st_ch_color_border()==''){$st_options3['st_ch_color_border'] = 'FFFFFF';}
if(st_ch_color_bg()==''){$st_options3['st_ch_color_bg'] = 'FFFFFF';}
if(st_ch_color_title()==''){$st_options3['st_ch_color_title'] = '000000';}
if(st_ch_color_site_link()==''){$st_options3['st_ch_color_site_link'] = '4D4D4D';}
if(st_ch_color_text()==''){$st_options3['st_ch_color_text'] = '4D4D4D';}
if(st_chitika_con1_head()==''){$st_options3['st_chitika_con1_head'] = '0';}
if(st_chitika_con1_bg()==''){$st_options3['st_chitika_con1_bg'] = 'div';}
if(st_chitika_lnk5_head()==''){$st_options3['st_chitika_lnk5_head'] = '0';}
if(st_chitika_lnk5_bg()==''){$st_options3['st_chitika_lnk5_bg'] = 'div';}
if(st_chitika_con6_pm()==''){$st_options3['st_chitika_con6_pm'] = '2';}
if(st_chitika_con1()==''){$st_options3['st_chitika_con1'] = '0';}
if(st_chitika_con2()==''){$st_options3['st_chitika_con2'] = '0';}
if(st_chitika_con3()==''){$st_options3['st_chitika_con3'] = '0';}
if(st_chitika_con4()==''){$st_options3['st_chitika_con4'] = '1';}
if(st_chitika_con6()==''){$st_options3['st_chitika_con6'] = '1';}
if(st_chitika_con6_sing()==''){$st_options3['st_chitika_con6_sing'] = '1';}
if(st_chitika_switch()==''){$st_options3['st_chitika_switch'] = '0';}
if(st_chitika_lnk5()==''){$st_options3['st_chitika_lnk5'] = '0';}
if(st_chitika_typ1()==''){$st_options3['st_chitika_typ1'] = '0';}
if(st_chitika_typ2()==''){$st_options3['st_chitika_typ2'] = '0';}
if(st_chitika_typ3()==''){$st_options3['st_chitika_typ3'] = '0';}
if(st_chitika_typ4()==''){$st_options3['st_chitika_typ4'] = '0';}
if(st_chitika_typ5()==''){$st_options3['st_chitika_typ5'] = '0';}
if(st_chitika_typ6()==''){$st_options3['st_chitika_typ6'] = '0';}
if(st_chitika_siz1()==''){$st_options3['st_chitika_siz1'] = '23';}
if(st_chitika_siz2()==''){$st_options3['st_chitika_siz2'] = '26';}
if(st_chitika_siz3()==''){$st_options3['st_chitika_siz3'] = '8';}
if(st_chitika_siz4()==''){$st_options3['st_chitika_siz4'] = '1';}
if(st_chitika_siz5()==''){$st_options3['st_chitika_siz5'] = '5';}
if(st_chitika_siz6()==''){$st_options3['st_chitika_siz6'] = '10';}
if(st_chitika_chan1()==''){$st_options3['st_chitika_chan1'] = '';}
if(st_chitika_chan2()==''){$st_options3['st_chitika_chan2'] = '';}
if(st_chitika_chan3()==''){$st_options3['st_chitika_chan3'] = '';}
if(st_chitika_chan4()==''){$st_options3['st_chitika_chan4'] = '';}
if(st_chitika_chan5()==''){$st_options3['st_chitika_chan5'] = '';}
if(st_chitika_chan6()==''){$st_options3['st_chitika_chan6'] = '';}
if(st_ch_alternate_ad_url()==''){$st_options3['st_ch_alternate_ad_url'] = '';}
update_option('theme-stallion-seo-theme-chitika', $st_options3);

$st_options4 = get_option('theme-stallion-seo-theme-clickbank');
if(st_cb_track()==''){$st_options4['st_cb_track'] = 'STALLION';}
if(st_cb_hopfeed_keyword_list()==''){$st_options4['st_cb_hopfeed_keyword_list'] = '';}
if(st_cb_keyword_auto()==''){$st_options4['st_cb_keyword_auto'] = '1';}
if(st_cb_hopfeed_font()==''){$st_options4['st_cb_hopfeed_font'] = 'Arial';}
if(st_cb_hopfeed_font_size()==''){$st_options4['st_cb_hopfeed_font_size'] = '12px';}
if(st_cb_hopfeed_font_color()==''){$st_options4['st_cb_hopfeed_font_color'] = '4D4D4D';}
if(st_cb_hopfeed_link_font_color()==''){$st_options4['st_cb_hopfeed_link_font_color'] = '000000';}
if(st_cb_hopfeed_link_font_hover_color()==''){$st_options4['st_cb_hopfeed_link_font_hover_color'] = '6A6A6A';}
if(st_cb_hopfeed_background_color()==''){$st_options4['st_cb_hopfeed_background_color'] = 'FFFFFF';}
if(st_cb_hopfeed_border_color()==''){$st_options4['st_cb_hopfeed_border_color'] = 'FFFFFF';}
if(st_cb_hopfeed_align()==''){$st_options4['st_cb_hopfeed_align'] = 'LEFT';}
if(st_cb_hopfeed_fill_slots()==''){$st_options4['st_cb_hopfeed_fill_slots'] = 'true';}
if(st_cb_hopfeed_cellpadding()==''){$st_options4['st_cb_hopfeed_cellpadding'] = '2';}
if(st_cb_con1()==''){$st_options4['st_cb_con1'] = '0';}
if(st_cb_float()==''){$st_options4['st_cb_float'] = 'fadleft';}
if(st_cb_con2()==''){$st_options4['st_cb_con2'] = '0';}
if(st_cb_con3()==''){$st_options4['st_cb_con3'] = '1';}
if(st_cb_con3_pm()==''){$st_options4['st_cb_con3_pm'] = '2';}
if(st_cb_con3_sing()==''){$st_options4['st_cb_con3_sing'] = '0';}
if(st_cb_con4()==''){$st_options4['st_cb_con4'] = '0';}
if(st_cb_con5()==''){$st_options4['st_cb_con5'] = '0';}
if(st_cb_con6()==''){$st_options4['st_cb_con6'] = '0';}
if(st_cb_siz1()==''){$st_options4['st_cb_siz1'] = '6';}
if(st_cb_siz2()==''){$st_options4['st_cb_siz2'] = '1';}
if(st_cb_siz3()==''){$st_options4['st_cb_siz3'] = '4';}
if(st_cb_siz4()==''){$st_options4['st_cb_siz4'] = '10';}
if(st_cb_siz5()==''){$st_options4['st_cb_siz5'] = '12';}
if(st_cb_siz6()==''){$st_options4['st_cb_siz6'] = '15';}
if(st_cb_side4_head()==''){$st_options4['st_cb_side4_head'] = '0';}
if(st_cb_side5_head()==''){$st_options4['st_cb_side5_head'] = '0';}
if(st_cb_side6_head()==''){$st_options4['st_cb_side6_head'] = '0';}
if(st_cb_side4_bg()==''){$st_options4['st_cb_side4_bg'] = 'div';}
if(st_cb_side5_bg()==''){$st_options4['st_cb_side5_bg'] = 'div';}
if(st_cb_side6_bg()==''){$st_options4['st_cb_side6_bg'] = 'div';}
if(st_stallion_link()==''){$st_options4['st_stallion_link'] = '1';}
update_option('theme-stallion-seo-theme-clickbank', $st_options4);

$st_options5 = get_option('theme-stallion-seo-theme-inlinks');
if(st_kontera_on()==''){$st_options5['st_kontera_on'] = '0';}
if(st_konteralink()==''){$st_options5['st_konteralink'] = '4D4D4D';}
if(st_infolinks_on()==''){$st_options5['st_infolinks_on'] = '0';}
if(st_linkwords_on()==''){$st_options5['st_linkwords_on'] = '0';}
if(st_infolinks_wsid()==''){$st_options5['st_infolinks_wsid'] = '0';}
if(st_infolinks_link_color()==''){$st_options5['st_infolinks_link_color'] = '000000';}
if(st_infolinks_title_color()==''){$st_options5['st_infolinks_title_color'] = '000000';}
if(st_infolinks_ad_link_color()==''){$st_options5['st_infolinks_ad_link_color'] = '000000';}
if(st_kontera_pubid()==''){$st_options5['st_kontera_pubid'] = '';}
if(st_infolinks_pid()==''){$st_options5['st_infolinks_pid'] = '';}
if(st_linkwords_pubid()==''){$st_options5['st_linkwords_pubid'] = '';}
update_option('theme-stallion-seo-theme-inlinks', $st_options5);

$st_options6 = get_option('theme-stallion-seo-theme-layout');
if(st_sidebar_lo()==''){$st_options6['st_sidebar_lo'] = '200l200r';}
if(st_post_lo()==''){$st_options6['st_post_lo'] = '0';}
if(st_header_hide()==''){$st_options6['st_header_hide'] = '1';}
if(st_title_hide()==''){$st_options6['st_title_hide'] = '1';}
if(st_header_2011_activate()==''){$st_options6['st_header_2011_activate'] = '0';}
if(st_header_2011_title()==''){$st_options6['st_header_2011_title'] = '0';}
if(st_tagline()==''){$st_options6['st_tagline'] = '1';}
if(st_search_form_hide()==''){$st_options6['st_search_form_hide'] = '1';}
if(st_author_link_hide()==''){$st_options6['st_author_link_hide'] = '0';}
if(st_author_bio()==''){$st_options6['st_author_bio'] = '0';}
if(st_post_tags()==''){$st_options6['st_post_tags'] = '1';}
if(st_post_dates_hide()==''){$st_options6['st_post_dates_hide'] = '1';}
if(st_commentst_post_dates_hide()==''){$st_options6['st_commentst_post_dates_hide'] = '1';}
if(st_commentlink()==''){$st_options6['st_commentlink'] = '1';}
if(st_admin_baroff()==''){$st_options6['st_admin_baroff'] = '1';}
if(st_nav_menu_photo()==''){$st_options6['st_nav_menu_photo'] = '0';}
if(st_nav_menu_photo_temp()==''){$st_options6['st_nav_menu_photo_temp'] = '0';}
if(st_nav_menu_on()==''){$st_options6['st_nav_menu_on'] = '1';}
if(st_nav_menu_on2()==''){$st_options6['st_nav_menu_on2'] = '0';}
if(st_nav_depth()==''){$st_options6['st_nav_depth'] = '0';}
if(st_home_nav_link()==''){$st_options6['st_home_nav_link'] = '0';}
if(st_include_exclude()==''){$st_options6['st_include_exclude'] = 'exclude';}
if(st_pages_in_exclude()==''){$st_options6['st_pages_in_exclude'] = '';}
if(st_extra_nav_links()==''){$st_options6['st_extra_nav_links'] = '';}
if(st_queries_used()==''){$st_options6['st_queries_used'] = '1';}
if(st_wp_codeshield()==''){$st_options6['st_wp_codeshield'] = '0';}
if(st_search_excerpt()==''){$st_options6['st_search_excerpt'] = '0';}
if(st_wp_generatoroff()==''){$st_options6['st_wp_generatoroff'] = 'off';}
if(st_wp_shortlink_wp_headoff()==''){$st_options6['st_wp_shortlink_wp_headoff'] = 'off';}
if(st_start_post_rel_linkoff()==''){$st_options6['st_start_post_rel_linkoff'] = 'off';}
if(st_adjacent_posts_rel_link_wp_headoff()==''){$st_options6['st_adjacent_posts_rel_link_wp_headoff'] = 'off';}
if(st_index_rel_linkoff()==''){$st_options6['st_index_rel_linkoff'] = 'off';}
if(st_parent_post_rel_linkoff()==''){$st_options6['st_parent_post_rel_linkoff'] = 'off';}
if(st_wlwmanifest_linkoff()==''){$st_options6['st_wlwmanifest_linkoff'] = 'off';}
if(st_rsd_linkoff()==''){$st_options6['st_rsd_linkoff'] = 'off';}
if(st_automatic_feedoff()==''){$st_options6['st_automatic_feedoff'] = 'off';}
if(st_wp_enqueue_scriptsoff()==''){$st_options6['st_wp_enqueue_scriptsoff'] = 'on';}
if(st_wp_print_head_scriptsoff()==''){$st_options6['st_wp_print_head_scriptsoff'] = 'on';}
if(st_wp_print_stylesoff()==''){$st_options6['st_wp_print_stylesoff'] = 'on';}
if(st_feed_linksoff()==''){$st_options6['st_feed_linksoff'] = 'on';}
if(st_feed_links_extraoff()==''){$st_options6['st_feed_links_extraoff'] = 'on';}
if(st_rel_canonicaloff()==''){$st_options6['st_rel_canonicaloff'] = 'on';}
update_option('theme-stallion-seo-theme-layout', $st_options6);

$st_options7 = get_option('theme-stallion-seo-theme-colours');
if(st_themecolor()==''){$st_options7['st_themecolor'] = 'black';}
if(st_banners_on()==''){$st_options7['st_banners_on'] = '1';}
if(st_banners_set()==''){$st_options7['st_banners_set'] = '01-default';}
if(st_banners_size()==''){$st_options7['st_banners_size'] = '10';}
if(st_banners_set_mid()==''){$st_options7['st_banners_set_mid'] = '03-artistic';}
if(st_banners_size_mid()==''){$st_options7['st_banners_size_mid'] = '10';}
if(st_header_bg_on()==''){$st_options7['st_header_bg_on'] = '1';}
if(st_header_bg_img()==''){$st_options7['st_header_bg_img'] = '1.jpg';}
if(st_header_2011_images()==''){$st_options7['st_header_2011_images'] = 'twenty-eleven';}
if(st_feature_slide()==''){$st_options7['st_feature_slide'] = '0';}
if(st_feature_slide_num()==''){$st_options7['st_feature_slide_num'] = '5';}
if(st_ft_effects()==''){$st_options7['st_ft_effects'] = 'zoom';}
if(st_ft_easings()==''){$st_options7['st_ft_easings'] = 'easeOutQuart';}
if(st_ft_timing()==''){$st_options7['st_ft_timing'] = '5000';}
if(st_ft_timing2()==''){$st_options7['st_ft_timing2'] = '2000';}
if(st_thumbs_admin()==''){$st_options7['st_thumbs_admin'] = '1';}
update_option('theme-stallion-seo-theme-colours', $st_options7);

$st_options8 = get_option('theme-stallion-seo-theme-promotion');
if(st_social_network()==''){$st_options8['st_social_network'] = '1';}
if(st_social_network_arch()==''){$st_options8['st_social_network_arch'] = '1';}
if(st_googlep1()==''){$st_options8['st_googlep1'] = '0';}
if(st_facebook()==''){$st_options8['st_facebook'] = '0';}
if(st_twitter()==''){$st_options8['st_twitter'] = '0';}
if(st_twitter_name()==''){$st_options8['st_twitter_name'] = '';}
if(st_flickr_widget()==''){$st_options8['st_flickr_widget'] = '1';}
if(st_youtube_widget()==''){$st_options8['st_youtube_widget'] = '1';}
if(st_google_trans_widget()==''){$st_options8['st_google_trans_widget'] = '1';}
if(st_bio_profile()==''){$st_options8['st_bio_profile'] = '0';}
if(st_bio_profile_position()==''){$st_options8['st_bio_profile_position'] = 'left';}
if(st_125px_widget()==''){$st_options8['st_125px_widget'] = '1';}
if(st_customad_widget()==''){$st_options8['st_customad_widget'] = '1';}
if(st_g_analytics()==''){$st_options8['st_g_analytics'] = '0';}
if(st_google_verify()==''){$st_options8['st_google_verify'] = '';}
if(st_bing_verify()==''){$st_options8['st_bing_verify'] = '';}
if(st_yahoo_verify()==''){$st_options8['st_yahoo_verify'] = '';}
if(st_g_analytics_ua()==''){$st_options8['st_g_analytics_ua'] = '';}
if(st_g_analytics_sub()==''){$st_options8['st_g_analytics_sub'] = '';}
update_option('theme-stallion-seo-theme-promotion', $st_options8);

$st_options9 = get_option('theme-stallion-seo-theme-seo-advanced');
if(st_super_comments()==''){$st_options9['st_super_comments'] = '0';}
if(st_super_comments_wds()==''){$st_options9['st_super_comments_wds'] = '400';}
if(st_super_comments_title()==''){$st_options9['st_super_comments_title'] = '12';}
if(st_super_comments_more()==''){$st_options9['st_super_comments_more'] = '5';}
if(st_super_comments_excerpt_length()==''){$st_options9['st_super_comments_excerpt_length'] = '40';}
if(st_comment_titles()==''){$st_options9['st_comment_titles'] = '0';}
if(st_seo_titles()==''){$st_options9['st_seo_titles'] = '1';}
if(st_seo_title_home()==''){$st_options9['st_seo_title_home'] = '';}
if(st_seo_plugin_desc()==''){$st_options9['st_seo_plugin_desc'] = '0';}
if(st_seo_plugin_key()==''){$st_options9['st_seo_plugin_key'] = '0';}
if(st_excerpt_length()==''){$st_options9['st_excerpt_length'] = '55';}
if(st_robot_noodpydir()==''){$st_options9['st_robot_noodpydir'] = '0';}
if(st_auto_thumbs()==''){$st_options9['st_auto_thumbs'] = '0';}
if(st_auto_thumb_align()=='fadleft'){$st_options9['st_auto_thumb_align'] = 'alignleft';} // Update old 6.0.1 setting
if(st_auto_thumb_align()=='fadright'){$st_options9['st_auto_thumb_align'] = 'alignright';} // Update old 6.0.1 setting
if(st_auto_thumb_align()==''){$st_options9['st_auto_thumb_align'] = 'alignleft';}
if(st_auto_thumb_wid()==''){$st_options9['st_auto_thumb_wid'] = '150';}
if(st_auto_thumb_hei()==''){$st_options9['st_auto_thumb_hei'] = '150';}
if(st_cloak_links()==''){$st_options9['st_cloak_links'] = '0';}
if(st_biography_links()==''){$st_options9['st_biography_links'] = '0';}
if(st_nofollow_content_links()==''){$st_options9['st_nofollow_content_links'] = '0';}
if(st_nofollow_comment_links()==''){$st_options9['st_nofollow_comment_links'] = '0';}
if(st_author_links()==''){$st_options9['st_author_links'] = '1';}
if(st_author_links_show()==''){$st_options9['st_author_links_show'] = '1';}
if(st_comment_links_html()==''){$st_options9['st_comment_links_html'] = '1';}
if(st_comment_nofollow()==''){$st_options9['st_comment_nofollow'] = '0';}
if(st_stupid_bots()==''){$st_options9['st_stupid_bots'] = '1';}
if(st_wprobot_seo()==''){$st_options9['st_wprobot_seo'] = '0';}
if(st_mppp_seo()==''){$st_options9['st_mppp_seo'] = '0';}
if(st_seo_plug_warn()==''){$st_options9['st_seo_plug_warn'] = '1';}
update_option('theme-stallion-seo-theme-seo-advanced', $st_options9);
}
?>
<?php 
{
st_stallion_update();
}
?><?php endif; ?>