<div class="st-profiles-<?php echo(st_bio_profile_position()); ?>">
<?php if(st_biography_links()==1 && st_cloak_links()==1){ ?>
<?php if(get_the_author_meta('st_pro_googleplus',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_googleplus',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/google-plus.png" alt="<?php bloginfo('name'); ?> Google Plus" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_facebook',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_facebook',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/facebook.png" alt="<?php bloginfo('name'); ?> Facebook" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_twitter',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_twitter',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/twitter.png" alt="<?php bloginfo('name'); ?> Twitter" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_linkedin',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_linkedin',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/linkedin.png" alt="<?php bloginfo('name'); ?> Linkedin" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_stumbleupon',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_stumbleupon',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/stumbleupon.png" alt="<?php bloginfo('name'); ?> StumbleUpon" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_youtube',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_youtube',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/youtube.png" alt="<?php bloginfo('name'); ?> YouTube Channel" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_flickr',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_flickr',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/flickr.png" alt="<?php bloginfo('name'); ?> Flickr" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_rssfeed',1)){ ?><span class="affst" title="tests" id="<?php the_author_meta('st_pro_rssfeed',1); ?>"><img src="<?php bloginfo('template_url'); ?>/images/ico/rss-feed.png" alt="<?php bloginfo('name'); ?> RSS Feed" width="32" height="32" class="st-profiles" /></span><br /><?php } ?>
<?php } else { ?>
<?php if(get_the_author_meta('st_pro_googleplus',1)){ ?><a href="<?php the_author_meta('st_pro_googleplus',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/google-plus.png" alt="<?php bloginfo('name'); ?> Google Plus" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_facebook',1)){ ?><a href="<?php the_author_meta('st_pro_facebook',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/facebook.png" alt="<?php bloginfo('name'); ?> Facebook" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_twitter',1)){ ?><a href="<?php the_author_meta('st_pro_twitter',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/twitter.png" alt="<?php bloginfo('name'); ?> Twitter" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_linkedin',1)){ ?><a href="<?php the_author_meta('st_pro_linkedin',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/linkedin.png" alt="<?php bloginfo('name'); ?> Linkedin" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_stumbleupon',1)){ ?><a href="<?php the_author_meta('st_pro_stumbleupon',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/stumbleupon.png" alt="<?php bloginfo('name'); ?> StumbleUpon" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_youtube',1)){ ?><a href="<?php the_author_meta('st_pro_youtube',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/youtube.png" alt="<?php bloginfo('name'); ?> YouTube Channel" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_flickr',1)){ ?><a href="<?php the_author_meta('st_pro_flickr',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/flickr.png" alt="<?php bloginfo('name'); ?> Flickr" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php if(get_the_author_meta('st_pro_rssfeed',1)){ ?><a href="<?php the_author_meta('st_pro_rssfeed',1); ?>" target="_blank"><img src="<?php bloginfo('template_url'); ?>/images/ico/rss-feed.png" alt="<?php bloginfo('name'); ?> RSS Feed" width="32" height="32" class="st-profiles" /></a><br /><?php } ?>
<?php } ?>
</div>